# NumPy Exercises

In [1]:
import numpy as np

## Problem 1:

In [4]:
# Problem 1
A = np.array([[3, -1, 4], [1, 5, -9]])
B = np.array([[2, 6, -5, 3], [5, -8, 9, 7], [9, -3, -2, -3]])
Prod = A @ B
print(Prod)

[[ 37  14 -32 -10]
 [-54  -7  58  65]]


## Problem 2:

In [24]:
# Define the function
def funcNumpy(A):
    out_mat = (- A @ A) @ A + 9 * (A @ A) - 15 * A
    return out_mat

# Input the matrix
A = np.array([[3, 1, 4], [1, 5, 9], [-5, 3, 1]])
print("A")
print(A)
# Call the function with A
B = funcNumpy(A)
print("B")
print(B)

A
[[ 3  1  4]
 [ 1  5  9]
 [-5  3  1]]
B
[[0 0 0]
 [0 0 0]
 [0 0 0]]


## Problem 3:

In [16]:
def writeMat():
    A = np.ones((7,7), dtype=np.int64)
    A = np.triu(A)
    B = np.full_like(A, 5)
    temp = np.full_like(A, -6)
    temp = np.tril(temp)
    B = B + temp
    prod = A @ B @ A
    return (A, B, prod)

(A, B, Prod) = writeMat()
print(A)
print(B)
print(Prod)

[[1 1 1 1 1 1 1]
 [0 1 1 1 1 1 1]
 [0 0 1 1 1 1 1]
 [0 0 0 1 1 1 1]
 [0 0 0 0 1 1 1]
 [0 0 0 0 0 1 1]
 [0 0 0 0 0 0 1]]
[[-1  5  5  5  5  5  5]
 [-1 -1  5  5  5  5  5]
 [-1 -1 -1  5  5  5  5]
 [-1 -1 -1 -1  5  5  5]
 [-1 -1 -1 -1 -1  5  5]
 [-1 -1 -1 -1 -1 -1  5]
 [-1 -1 -1 -1 -1 -1 -1]]
[[ -7  -8  -3   8  25  48  77]
 [ -6 -12 -12  -6   6  24  48]
 [ -5 -10 -15 -14  -7   6  25]
 [ -4  -8 -12 -16 -14  -6   8]
 [ -3  -6  -9 -12 -15 -12  -3]
 [ -2  -4  -6  -8 -10 -12  -8]
 [ -1  -2  -3  -4  -5  -6  -7]]


## Problem 4

In [26]:
def fancyIndexing(in_arr):
    out_arr = np.copy(in_arr)
    mask = out_arr < 0
    out_arr[mask] = 0
    return out_arr

A = np.zeros((2,3))
B = np.ones_like(A)
B1 = np.triu(B)
B2 = np.tril(B)
B1 = B1 * 2
B2 = B2 * -5
A = A + B1 + B2
print("A:")
print(A)
C = fancyIndexing(A)
print("A after fancy indexing:")
print(C)

A:
[[-3.  2.  2.]
 [-5. -3.  2.]]
A after fancy indexing:
[[0. 2. 2.]
 [0. 0. 2.]]


## Problem 5

In [22]:
def matABC():
    A = np.arange(6).reshape((3,2))
    A = A.T
    B = np.full((3,3), 3)
    B = np.tril(B)
    C = np.diag([-2, -2, -2])
    return (A, B, C)

(A, B, C) = matABC()
print("A")
print(A)
print("B")
print(B)
print("C")
print(C)
I = np.eye(3)
O_3_3 = np.zeros((3,3))
O_2_2 = np.zeros((2,2))
O_3_2 = np.zeros((3,2))
O_2_3 = np.zeros((2,3))
out = np.hstack((np.vstack((np.zeros((3,3)), A, B)), np.vstack((A.T, np.zeros((2,2)), np.zeros((3,2)))), np.vstack((I, np.zeros((2,3)), C))))
print("out")
print(out)

A
[[0 2 4]
 [1 3 5]]
B
[[3 0 0]
 [3 3 0]
 [3 3 3]]
C
[[-2  0  0]
 [ 0 -2  0]
 [ 0  0 -2]]
out
[[ 0.  0.  0.  0.  1.  1.  0.  0.]
 [ 0.  0.  0.  2.  3.  0.  1.  0.]
 [ 0.  0.  0.  4.  5.  0.  0.  1.]
 [ 0.  2.  4.  0.  0.  0.  0.  0.]
 [ 1.  3.  5.  0.  0.  0.  0.  0.]
 [ 3.  0.  0.  0.  0. -2.  0.  0.]
 [ 3.  3.  0.  0.  0.  0. -2.  0.]
 [ 3.  3.  3.  0.  0.  0.  0. -2.]]


## Problem 6

In [33]:
def stochastic(in_mat):
    row_sum = in_mat.sum(axis=1)
    n = row_sum.size
    row_sum = row_sum.reshape(n,1)
    out_mat = np.copy(in_mat)
    out_mat = out_mat / row_sum
    return out_mat
A = np.array([[0, 2, 3], [4, 1, 5]])
print("A:")
print(A)
B = stochastic(A)
print("Row stochastic of A:")
print(B)

A:
[[0 2 3]
 [4 1 5]]
Row stochastic of A:
[[0.  0.4 0.6]
 [0.4 0.1 0.5]]


## Problem 7

In [44]:
grid = np.load("grid.npy")
(r,c) = grid.shape
# Initiate the output to 0
max_prod_4 = 0
# Loop across the grid for all combinations of 4x4 matrices
for i in range(r-3):
    for j in range(c-3):
        # Down
        Down = grid[i, j] * grid[i, j+1] * grid[i, j+2] * grid[i, j+3]
        # Right
        Right = grid[i, j] * grid[i+1, j] * grid[i+2, j] * grid[i+3, j]
        # Diagonal
        Diag = grid[i, j] * grid[i+1, j+1] * grid[i+2, j+2] * grid[i+3, j+3]
        max_prod_4 = np.max([max_prod_4, Down, Right, Diag])
print("Greatest product of four adjacent numbers is: " + str (max_prod_4))

Greatest product of four adjacent numbers is: 51267216
